name: Keep API Alive

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes
  workflow_dispatch:          # allows manual trigger from Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API
        run: curl -s https://tic-tac-toe-1-d5cb.onrender.com/ > /dev/null
